# Generated by Django 2.1.7 on 2019-03-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productinfo',
            fields=[
                ('sl_no', models.IntegerField()),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name_of_product', models.CharField(max_length=255)),
                ('type_of_product', models.CharField(max_length=100)),
                ('firmware_version', models.CharField(max_length=50)),
                ('os_supported', models.CharField(max_length=100)),
                ('supported_protocols', models.CharField(max_length=255)),
                ('max_firmware_support', models.CharField(max_length=100)),
                ('env_support', models.CharField(max_length=100)),
                ('power_capability', models.CharField(max_length=50)),
                ('pricing', models.BigIntegerField()),
                ('configurable', models.IntegerField()),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
