# Generated by Django 2.1.7 on 2019-03-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MARC', '0002_productfeedback_productionproductinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfeedback',
            name='product_quality',
            field=models.CharField(choices=[(1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')], max_length=10),
        ),
        migrations.AlterField(
            model_name='productfeedback',
            name='suggestions',
            field=models.TextField(),
        ),
    ]
