# Generated by Django 2.1.7 on 2019-03-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MARC', '0003_auto_20190316_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfeedback',
            name='product_quality',
            field=models.CharField(choices=[('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], max_length=10),
        ),
    ]
