# Generated by Django 2.1.7 on 2019-04-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MARC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.IntegerField(default=0)),
                ('product_type', models.CharField(default='Home Automation', max_length=255)),
                ('prod_id', models.CharField(default='HA123', max_length=20)),
                ('category', models.IntegerField(default=0)),
                ('status', models.CharField(default='complete', max_length=20)),
            ],
        ),
    ]
